//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirstApproach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Emailid { get; set; }
        public string Mobileno { get; set; }
        public string Adress { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<System.DateTime> DtaeOfReleiving { get; set; }
        public string State { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> DegreeId { get; set; }
        public Nullable<int> SpecializationId { get; set; }
        public string Photo { get; set; }
        public string Experience { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
    }
}
